spring:
  datasource:
    url: jdbc:postgresql://postgres-y9ks.railway.internal:5430/railway
    username: postgres
    password: sJHxympgNvkKEbVvtuXIwYAfjQHtWWMB
    driver-class-name: org.postgresql.Driver  # Adicionando a classe do driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Adicionando o dialeto do Hibernate